### ISSUE TITLE
Request: Provide a sample for testing

### ISSUE THREAD

**Issue by vdun** [airbus-cert/cacdec#1]

**Comment by citronneur** [comment]
Hi vdun,

In commit db01152 we added example file produce from an up to date Windows 10 install. We have also fixed some issues.
Now just after followed install steps,  just launch __cacdec__ script and produce artifacts like :
![Capture](https://user-images.githubusercontent.com/5627503/76220979-a4181400-6218-11ea-9725-b6afd0e374d5.PNG)

Thanks for your request, and enjoy cacdec.
